//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.Handlers {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Messages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Cedar.Handlers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has occurred when dispatching a commit {0}..
        /// </summary>
        internal static string ExceptionHasOccuredWhenDispatchingACommit {
            get {
                return ResourceManager.GetString("ExceptionHasOccuredWhenDispatchingACommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be negative..
        /// </summary>
        internal static string NegativeDuration {
            get {
                return ResourceManager.GetString("NegativeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry interval cannot be negative..
        /// </summary>
        internal static string NegativeRetryInterval {
            get {
                return ResourceManager.GetString("NegativeRetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TransientException has occured {0} times and exceeded the retry policy duration of {0}..
        /// </summary>
        internal static string TransientExceptionExceededDuration {
            get {
                return ResourceManager.GetString("TransientExceptionExceededDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TransientException has occured {0} times..
        /// </summary>
        internal static string TransientExceptionOccured {
            get {
                return ResourceManager.GetString("TransientExceptionOccured", resourceCulture);
            }
        }
    }
}
